version: '3.0'
services:
  puppet:
    hostname: puppet
    image: puppetlabs/puppetserver-standalone
    ports:
      - 8140:8140
    volumes:
      - './:/etc/puppetlabs/code/environments/production'
